version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: currency-api:latest
    container_name: currency-api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - .:/app
    restart: unless-stopped
